package com.flight_reservation_app.utilities;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;

import org.springframework.stereotype.Component;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Component
public class PdfGenerator {
	private static String FILE = "c:/temp/FirstPdf.pdf";
	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);

	private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

	public void generatePDF(String filePath, String name, String emailid,String phone,String operatingAirlines,String departureDate,String departureCity,String arrivalCity) {

		try {
			Document document = new Document();
			PdfWriter.getInstance(document, new FileOutputStream(filePath));
			document.open();
			addMetaData(document);
			addTitleAndTable(document, name, emailid,phone,operatingAirlines,departureDate,departureCity,arrivalCity);
			
			document.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	

	private static void addTitleAndTable(Document document, String name, String emailid, String phone,
			String operatingAirlines, String departureDate, String departureCity, String arrivalCity)throws DocumentException {
		Paragraph preface = new Paragraph();

		preface.add(new Paragraph("Flight Booking Details", catFont));
		preface.add(new Paragraph(
                "Report generated by: " +"  " +"Flight Reservation Company " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
		document.add(preface);
		document.add(Chunk.NEWLINE);
		document.add(Chunk.NEWLINE);
		PdfPTable table = new PdfPTable(2);
		table.setWidthPercentage(100);
		   PdfPCell c1 = new PdfPCell(new Phrase("Passenger Detail"));
	        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
	        c1.setColspan(2);
	        table.addCell(c1);
	        
	        table.addCell("Passenger Name");
	        table.addCell(name);
	        table.addCell("Email Id");
	        table.addCell(emailid);
	        table.addCell("Phone Number");
	        table.addCell(phone);
	        
	        document.add(table);
	        
	        PdfPTable table1=new PdfPTable(2);
	        table1.setWidthPercentage(100);
	        PdfPCell c2 = new PdfPCell(new Phrase("Flight Detail"));
	        c2.setHorizontalAlignment(Element.ALIGN_CENTER);
	        c2.setColspan(2);
	        table1.addCell(c2);
	        
	        table1.addCell("Operating Airlines");
	        table1.addCell(operatingAirlines);
	        table1.addCell("departure Date"); 
	        table1.addCell(departureDate);
	        table1.addCell("departure City");
	        table1.addCell(departureCity);
	        table1.addCell("Arrival city");
	        table1.addCell(arrivalCity);
	        document.add(table1);
	        document.close();
	        
	}



	

	private static void addMetaData(Document document) {
		document.addTitle("Confirm Reservartion");
		document.addSubject("Ticket has been booked");
		document.addKeywords("Java,pdf,itext");
		document.addCreator("booker");
	}

}
